name: Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup Java JDK and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        run: |
          mvn -B verify --file starlight/pom.xml --no-transfer-progress 
          mvn -B verify --file spring-cloud-starter-baidu-starlight/pom.xml --no-transfer-progress

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
